version: 2

sources:
  - name: s_zernio
    schema: s_zernio
    tables:
      - name: linkedin_posts
      - name: linkedin_post_analytics

  - name: s_linkedin
    schema: s_linkedin
    tables:
      - name: ugc_posts
      - name: social_action_likes
      - name: social_action_comments

  - name: s_buffer
    schema: s_buffer
    tables:
      - name: posts
      - name: channels
