-- Extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

-- Source schemas (raw ingestion)
CREATE SCHEMA IF NOT EXISTS s_reddit;
CREATE SCHEMA IF NOT EXISTS s_slack;
CREATE SCHEMA IF NOT EXISTS s_substack;
CREATE SCHEMA IF NOT EXISTS s_meetup;
CREATE SCHEMA IF NOT EXISTS s_euro_stat;
CREATE SCHEMA IF NOT EXISTS s_yahoo_finance;
CREATE SCHEMA IF NOT EXISTS s_wordpress;
CREATE SCHEMA IF NOT EXISTS s_linkedin;
CREATE SCHEMA IF NOT EXISTS s_analytics;
CREATE SCHEMA IF NOT EXISTS s_notion;
CREATE SCHEMA IF NOT EXISTS s_zernio;
CREATE SCHEMA IF NOT EXISTS s_buffer;
CREATE SCHEMA IF NOT EXISTS s_manual;
CREATE SCHEMA IF NOT EXISTS s_motherduck;

-- Other schemas
CREATE SCHEMA IF NOT EXISTS prediction;
CREATE SCHEMA IF NOT EXISTS training;
CREATE SCHEMA IF NOT EXISTS t_content_generation;
CREATE SCHEMA IF NOT EXISTS m_staging;
CREATE SCHEMA IF NOT EXISTS m_fact;
CREATE SCHEMA IF NOT EXISTS m_episodic;
CREATE SCHEMA IF NOT EXISTS m_embeddings;
